#!/bin/sh

set -o errexit

cd "`dirname \"$0\"`/"
. prepare

mklib ffi
mklib gettext
mklib glib

mkcd "${BUILD_DIR}fluidsynth"
"${TP_DIR}cmake/bin/cmake"                              \
	-DCMAKE_INSTALL_PREFIX="${LIBS_DIR}"                \
	-DCMAKE_OSX_DEPLOYMENT_TARGET="10.7"                \
 	-DCMAKE_OSX_SYSROOT="${SYSROOT_DIR}"                \
 	-DCMAKE_SHARED_LINKER_FLAGS="${CMAKE_LINKER_FLAGS}" \
 	-Denable-framework=NO                               \
 	-DLIB_SUFFIX=""                                     \
	"${FS_DIR}"
make install

if [ -e "${DIST_DIR}" ]; then
	rm -r "${DIST_DIR}"
fi

mkcd "${DIST_DIR}"
cp "${LIBS_DIR}lib/libfluidsynth.1.dylib" .

for FN in AUTHORS COPYING NEWS README THANKS; do
	cp "${FS_DIR}$FN" .
done

DMG_NAME=FluidSynth-`"${LIBS_DIR}/bin/fluidsynth" --version | awk '/FluidSynth version [0-9.]*/ { print $3 }'`
DMG_PATH=${ROOT_DIR}${DMG_NAME}.dmg

mkdmg "${DMG_PATH}" "${DMG_NAME}"
