#!/bin/sh

set -o errexit

cd "`dirname \"$0\"`/"
. prepare

mkcd "${BUILD_DIR}openal-soft"
"${TP_DIR}cmake/bin/cmake"      \
	${CMAKE_COMMON_OPTS}        \
	-DLIBTYPE="STATIC"          \
	-DALSOFT_CPUEXT_SSE4_1="NO" \
	"${TP_DIR}openal-soft"
make install

cd "${ROOT_DIR}"

if [ ! -e gzdoom ]; then
	git clone https://github.com/coelckers/gzdoom.git
fi

cd "${ROOT_DIR}gzdoom"

if [ -n "$1" ]; then
	git checkout "$1"
else
	git checkout master
fi

if [ "${1:0:4}" != "tags" ]; then
	git pull
fi

mkcd "${BUILD_DIR}gzdoom"
"${TP_DIR}cmake/bin/cmake"                           \
	${CMAKE_COMMON_OPTS}                             \
	-DCMAKE_EXE_LINKER_FLAGS="${CMAKE_LINKER_FLAGS}" \
	-DFMOD_INCLUDE_DIR=${FMOD_DIR}inc                \
	-DFMOD_LIBRARY=${FMOD_DIR}lib/libfmodex.dylib    \
	-DDYN_OPENAL=NO                                  \
	"${ROOT_DIR}gzdoom"
make

if [ -e "${DIST_DIR}" ]; then
	rm -r "${DIST_DIR}"
fi

mkdir "${DIST_DIR}"
cp -R gzdoom.app "${DIST_DIR}GZDoom.app"
cp -R "${ROOT_DIR}gzdoom/docs" "${DIST_DIR}Docs"
ln -s /Applications "${DIST_DIR}/Applications"

cd "${ROOT_DIR}gzdoom"
DMG_NAME=GZDoom-`git describe --tags`
DMG_PATH=${ROOT_DIR}/${DMG_NAME}.dmg

mkdmg "${DMG_PATH}" "${DMG_NAME}"
