#!/bin/sh

set -o errexit

cd "`dirname \"$0\"`/.."
. scripts/prepare

mkcd "${BUILD_DIR}openal-soft"
"${TP_DIR}cmake/bin/cmake"      \
	${CMAKE_COMMON_OPTS}        \
	-DLIBTYPE="STATIC"          \
	-DALSOFT_CPUEXT_SSE4_1="NO" \
	"${TP_DIR}openal-soft"
make install

cd "${ROOT_DIR}"

if [ ! -e gzdoom ]; then
	git clone https://github.com/coelckers/gzdoom.git
fi

cd "${ROOT_DIR}gzdoom"

if [ -n "$1" ]; then
	git checkout "$1"
else
	git checkout master
fi

set +o errexit
git symbolic-ref HEAD 2>&1 >/dev/null
CANT_PULL=$?
set -o errexit

if [ ${CANT_PULL} -eq 0 ]; then
	git pull
fi

mkcd "${BUILD_DIR}gzdoom"
"${TP_DIR}cmake/bin/cmake"                           \
	${CMAKE_COMMON_OPTS}                             \
	-DCMAKE_BUILD_TYPE=RelWithDebInfo                \
	-DCMAKE_EXE_LINKER_FLAGS="${CMAKE_LINKER_FLAGS}" \
	-DFMOD_INCLUDE_DIR=${FMOD_DIR}inc                \
	-DFMOD_LIBRARY=${FMOD_DIR}lib/libfmodex.dylib    \
	-DDYN_OPENAL=NO                                  \
	"${ROOT_DIR}gzdoom"
make

if [ -e "${DIST_DIR}" ]; then
	rm -r "${DIST_DIR}"
fi

BUNDLE_PATH=${DIST_DIR}GZDoom.app
INFO_PLIST_PATH=${BUNDLE_PATH}/Contents/Info.plist

mkdir "${DIST_DIR}"
cp -R gzdoom.app "${BUNDLE_PATH}"
cp -R "${ROOT_DIR}gzdoom/docs" "${DIST_DIR}Docs"
ln -s /Applications "${DIST_DIR}/Applications"

FMODEX_DYLIB=${BUNDLE_PATH}/Contents/Frameworks/libfmodex.dylib
CURRENT_ARCH=x86_64

lipo "${FMODEX_DYLIB}" -extract ${CURRENT_ARCH} -output ${CURRENT_ARCH}.dylib
rm "${FMODEX_DYLIB}"
mv ${CURRENT_ARCH}.dylib "${FMODEX_DYLIB}"

cd "${ROOT_DIR}gzdoom"
VERSION=`git describe --tags`

plutil -replace LSMinimumSystemVersion -string "${MIN_VERSION}" "${INFO_PLIST_PATH}"
plutil -replace CFBundleVersion -string "${VERSION}" "${INFO_PLIST_PATH}"
plutil -replace CFBundleShortVersionString -string "${VERSION}" "${INFO_PLIST_PATH}"
plutil -replace CFBundleLongVersionString -string "${VERSION}" "${INFO_PLIST_PATH}"

DMG_NAME=GZDoom-${VERSION}
DMG_PATH=${ROOT_DIR}`echo ${DMG_NAME} | tr '[:upper:]' '[:lower:]'`.dmg

mkdmg "${DMG_PATH}" "${DMG_NAME}"
